services:
  postgres:
    image: postgres:16-alpine
    container_name: efsora-postgres
    environment:
      POSTGRES_DB: envanter_db
      POSTGRES_USER: efsora_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U efsora_user -d envanter_db"]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: efsora-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/envanter_db
      SPRING_DATASOURCE_USERNAME: efsora_user
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8081:8081"
    restart: unless-stopped

volumes:
  postgres_data: